// @generated by protoc-gen-es v1.7.2
// @generated from file response/next.proto (package youtube.response.next, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Content as Content$1 } from "./browse_pb.js";

/**
 * @generated from message youtube.response.next.Next
 */
export const Next = proto3.makeMessageType(
  "youtube.response.next.Next",
  () => [
    { no: 7, name: "content", kind: "message", T: Content },
    { no: 8, name: "onResponseReceivedAction", kind: "message", T: Content$1 },
  ],
);

/**
 * @generated from message youtube.response.next.Content
 */
export const Content = proto3.makeMessageType(
  "youtube.response.next.Content",
  () => [
    { no: 51779735, name: "nextResults", kind: "message", T: NextResults },
  ],
);

/**
 * @generated from message youtube.response.next.NextResults
 */
export const NextResults = proto3.makeMessageType(
  "youtube.response.next.NextResults",
  () => [
    { no: 1, name: "content", kind: "message", T: Content$1 },
  ],
);

