// @generated by protoc-gen-es v1.7.2
// @generated from file response/next.proto (package youtube.response.next, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Content as Content$1 } from "./browse_pb.js";

/**
 * @generated from message youtube.response.next.Next
 */
export declare class Next extends Message<Next> {
  /**
   * @generated from field: youtube.response.next.Content content = 7;
   */
  content?: Content;

  /**
   * @generated from field: youtube.response.browse.Content onResponseReceivedAction = 8;
   */
  onResponseReceivedAction?: Content$1;

  constructor(data?: PartialMessage<Next>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.next.Next";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Next;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Next;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Next;

  static equals(a: Next | PlainMessage<Next> | undefined, b: Next | PlainMessage<Next> | undefined): boolean;
}

/**
 * @generated from message youtube.response.next.Content
 */
export declare class Content extends Message<Content> {
  /**
   * @generated from field: youtube.response.next.NextResults nextResults = 51779735;
   */
  nextResults?: NextResults;

  constructor(data?: PartialMessage<Content>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.next.Content";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Content;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Content;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Content;

  static equals(a: Content | PlainMessage<Content> | undefined, b: Content | PlainMessage<Content> | undefined): boolean;
}

/**
 * @generated from message youtube.response.next.NextResults
 */
export declare class NextResults extends Message<NextResults> {
  /**
   * @generated from field: youtube.response.browse.Content content = 1;
   */
  content?: Content$1;

  constructor(data?: PartialMessage<NextResults>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.next.NextResults";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): NextResults;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): NextResults;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): NextResults;

  static equals(a: NextResults | PlainMessage<NextResults> | undefined, b: NextResults | PlainMessage<NextResults> | undefined): boolean;
}

