// @generated by protoc-gen-es v1.7.2
// @generated from file response/player.proto (package youtube.response.player, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.response.player.Player
 */
export declare class Player extends Message<Player> {
  /**
   * @generated from field: repeated youtube.response.player.AdPlacement adPlacements = 7;
   */
  adPlacements: AdPlacement[];

  /**
   * @generated from field: repeated youtube.response.player.AdSlot adSlots = 68;
   */
  adSlots: AdSlot[];

  /**
   * @generated from field: youtube.response.player.PlayabilityStatus playabilityStatus = 2;
   */
  playabilityStatus?: PlayabilityStatus;

  /**
   * @generated from field: youtube.response.player.PlaybackTracking playbackTracking = 9;
   */
  playbackTracking?: PlaybackTracking;

  /**
   * @generated from field: youtube.response.player.Captions captions = 10;
   */
  captions?: Captions;

  constructor(data?: PartialMessage<Player>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.Player";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Player;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Player;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Player;

  static equals(a: Player | PlainMessage<Player> | undefined, b: Player | PlainMessage<Player> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.AdPlacement
 */
export declare class AdPlacement extends Message<AdPlacement> {
  /**
   * @generated from field: youtube.response.player.AdPlacementRenderer adPlacementRenderer = 84813246;
   */
  adPlacementRenderer?: AdPlacementRenderer;

  constructor(data?: PartialMessage<AdPlacement>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.AdPlacement";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdPlacement;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdPlacement;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdPlacement;

  static equals(a: AdPlacement | PlainMessage<AdPlacement> | undefined, b: AdPlacement | PlainMessage<AdPlacement> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.AdPlacementRenderer
 */
export declare class AdPlacementRenderer extends Message<AdPlacementRenderer> {
  /**
   * @generated from field: string params = 4;
   */
  params: string;

  constructor(data?: PartialMessage<AdPlacementRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.AdPlacementRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdPlacementRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdPlacementRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdPlacementRenderer;

  static equals(a: AdPlacementRenderer | PlainMessage<AdPlacementRenderer> | undefined, b: AdPlacementRenderer | PlainMessage<AdPlacementRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.PlayabilityStatus
 */
export declare class PlayabilityStatus extends Message<PlayabilityStatus> {
  /**
   * @generated from field: youtube.response.player.PictureInPictureSupportedRenderer pictureInPictureRender = 21;
   */
  pictureInPictureRender?: PictureInPictureSupportedRenderer;

  /**
   * @generated from field: youtube.response.player.BackgroundSupportedRenderer backgroundPlayerRender = 11;
   */
  backgroundPlayerRender?: BackgroundSupportedRenderer;

  constructor(data?: PartialMessage<PlayabilityStatus>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.PlayabilityStatus";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PlayabilityStatus;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PlayabilityStatus;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PlayabilityStatus;

  static equals(a: PlayabilityStatus | PlainMessage<PlayabilityStatus> | undefined, b: PlayabilityStatus | PlainMessage<PlayabilityStatus> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.PictureInPictureSupportedRenderer
 */
export declare class PictureInPictureSupportedRenderer extends Message<PictureInPictureSupportedRenderer> {
  /**
   * @generated from field: youtube.response.player.PictureInPictureAbility pictureInPictureAbility = 151635310;
   */
  pictureInPictureAbility?: PictureInPictureAbility;

  constructor(data?: PartialMessage<PictureInPictureSupportedRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.PictureInPictureSupportedRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PictureInPictureSupportedRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PictureInPictureSupportedRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PictureInPictureSupportedRenderer;

  static equals(a: PictureInPictureSupportedRenderer | PlainMessage<PictureInPictureSupportedRenderer> | undefined, b: PictureInPictureSupportedRenderer | PlainMessage<PictureInPictureSupportedRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.BackgroundSupportedRenderer
 */
export declare class BackgroundSupportedRenderer extends Message<BackgroundSupportedRenderer> {
  /**
   * @generated from field: youtube.response.player.BackgroundAbility backgroundAbility = 64657230;
   */
  backgroundAbility?: BackgroundAbility;

  constructor(data?: PartialMessage<BackgroundSupportedRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.BackgroundSupportedRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BackgroundSupportedRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BackgroundSupportedRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BackgroundSupportedRenderer;

  static equals(a: BackgroundSupportedRenderer | PlainMessage<BackgroundSupportedRenderer> | undefined, b: BackgroundSupportedRenderer | PlainMessage<BackgroundSupportedRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.PictureInPictureAbility
 */
export declare class PictureInPictureAbility extends Message<PictureInPictureAbility> {
  /**
   * @generated from field: bool active = 1;
   */
  active: boolean;

  /**
   * @generated from field: int32 f4 = 4;
   */
  f4: number;

  /**
   * @generated from field: int32 f6 = 6;
   */
  f6: number;

  /**
   * @generated from field: int32 f8 = 8;
   */
  f8: number;

  constructor(data?: PartialMessage<PictureInPictureAbility>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.PictureInPictureAbility";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PictureInPictureAbility;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PictureInPictureAbility;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PictureInPictureAbility;

  static equals(a: PictureInPictureAbility | PlainMessage<PictureInPictureAbility> | undefined, b: PictureInPictureAbility | PlainMessage<PictureInPictureAbility> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.BackgroundAbility
 */
export declare class BackgroundAbility extends Message<BackgroundAbility> {
  /**
   * @generated from field: bool active = 1;
   */
  active: boolean;

  constructor(data?: PartialMessage<BackgroundAbility>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.BackgroundAbility";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BackgroundAbility;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BackgroundAbility;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BackgroundAbility;

  static equals(a: BackgroundAbility | PlainMessage<BackgroundAbility> | undefined, b: BackgroundAbility | PlainMessage<BackgroundAbility> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.PlaybackTracking
 */
export declare class PlaybackTracking extends Message<PlaybackTracking> {
  /**
   * @generated from field: youtube.response.player.Url videostatsPlaybackUrl = 1;
   */
  videostatsPlaybackUrl?: Url;

  /**
   * @generated from field: youtube.response.player.Url videostatsDelayplayUrl = 2;
   */
  videostatsDelayplayUrl?: Url;

  /**
   * @generated from field: youtube.response.player.Url videostatsWatchtimeUrl = 3;
   */
  videostatsWatchtimeUrl?: Url;

  /**
   * @generated from field: youtube.response.player.Url ptrackingUrl = 4;
   */
  ptrackingUrl?: Url;

  /**
   * @generated from field: youtube.response.player.Url qoeUrl = 5;
   */
  qoeUrl?: Url;

  /**
   * @generated from field: youtube.response.player.Url atrUrl = 13;
   */
  atrUrl?: Url;

  /**
   * @generated from field: youtube.response.player.Url videostatsEngageUrl = 15;
   */
  videostatsEngageUrl?: Url;

  /**
   * @generated from field: youtube.response.player.Url pageadViewthroughconversion = 18;
   */
  pageadViewthroughconversion?: Url;

  constructor(data?: PartialMessage<PlaybackTracking>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.PlaybackTracking";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PlaybackTracking;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PlaybackTracking;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PlaybackTracking;

  static equals(a: PlaybackTracking | PlainMessage<PlaybackTracking> | undefined, b: PlaybackTracking | PlainMessage<PlaybackTracking> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.Url
 */
export declare class Url extends Message<Url> {
  /**
   * @generated from field: string baseUrl = 1;
   */
  baseUrl: string;

  constructor(data?: PartialMessage<Url>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.Url";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Url;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Url;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Url;

  static equals(a: Url | PlainMessage<Url> | undefined, b: Url | PlainMessage<Url> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.AdSlot
 */
export declare class AdSlot extends Message<AdSlot> {
  /**
   * @generated from field: youtube.response.player.AdSlot.Render render = 424701016;
   */
  render?: AdSlot_Render;

  constructor(data?: PartialMessage<AdSlot>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.AdSlot";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdSlot;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdSlot;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdSlot;

  static equals(a: AdSlot | PlainMessage<AdSlot> | undefined, b: AdSlot | PlainMessage<AdSlot> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.AdSlot.Render
 */
export declare class AdSlot_Render extends Message<AdSlot_Render> {
  constructor(data?: PartialMessage<AdSlot_Render>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.AdSlot.Render";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdSlot_Render;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdSlot_Render;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdSlot_Render;

  static equals(a: AdSlot_Render | PlainMessage<AdSlot_Render> | undefined, b: AdSlot_Render | PlainMessage<AdSlot_Render> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.Captions
 */
export declare class Captions extends Message<Captions> {
  /**
   * @generated from field: youtube.response.player.PlayerCaptionsTrackListRenderer playerCaptionsTrackListRenderer = 51621377 [json_name = "playerCaptionsTracklistRenderer"];
   */
  playerCaptionsTrackListRenderer?: PlayerCaptionsTrackListRenderer;

  constructor(data?: PartialMessage<Captions>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.Captions";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Captions;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Captions;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Captions;

  static equals(a: Captions | PlainMessage<Captions> | undefined, b: Captions | PlainMessage<Captions> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.PlayerCaptionsTrackListRenderer
 */
export declare class PlayerCaptionsTrackListRenderer extends Message<PlayerCaptionsTrackListRenderer> {
  /**
   * @generated from field: repeated youtube.response.player.CaptionTrack captionTracks = 1;
   */
  captionTracks: CaptionTrack[];

  /**
   * @generated from field: repeated youtube.response.player.AudioTrack audioTracks = 2;
   */
  audioTracks: AudioTrack[];

  /**
   * @generated from field: repeated youtube.response.player.TranslationLanguage translationLanguages = 3;
   */
  translationLanguages: TranslationLanguage[];

  /**
   * @generated from field: optional int32 defaultAudioTrackIndex = 4;
   */
  defaultAudioTrackIndex?: number;

  /**
   * @generated from field: optional int32 defaultCaptionTrackIndex = 6;
   */
  defaultCaptionTrackIndex?: number;

  constructor(data?: PartialMessage<PlayerCaptionsTrackListRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.PlayerCaptionsTrackListRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PlayerCaptionsTrackListRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PlayerCaptionsTrackListRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PlayerCaptionsTrackListRenderer;

  static equals(a: PlayerCaptionsTrackListRenderer | PlainMessage<PlayerCaptionsTrackListRenderer> | undefined, b: PlayerCaptionsTrackListRenderer | PlainMessage<PlayerCaptionsTrackListRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.CaptionTrack
 */
export declare class CaptionTrack extends Message<CaptionTrack> {
  /**
   * @generated from field: string baseUrl = 1;
   */
  baseUrl: string;

  /**
   * @generated from field: youtube.response.player.Name name = 2;
   */
  name?: Name;

  /**
   * @generated from field: string vssId = 3;
   */
  vssId: string;

  /**
   * @generated from field: string languageCode = 4;
   */
  languageCode: string;

  /**
   * @generated from field: optional string kind = 5;
   */
  kind?: string;

  /**
   * @generated from field: optional bool rtl = 6;
   */
  rtl?: boolean;

  /**
   * @generated from field: bool isTranslatable = 7;
   */
  isTranslatable: boolean;

  constructor(data?: PartialMessage<CaptionTrack>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.CaptionTrack";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CaptionTrack;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CaptionTrack;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CaptionTrack;

  static equals(a: CaptionTrack | PlainMessage<CaptionTrack> | undefined, b: CaptionTrack | PlainMessage<CaptionTrack> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.AudioTrack
 */
export declare class AudioTrack extends Message<AudioTrack> {
  /**
   * @generated from field: repeated int32 captionTrackIndices = 2 [packed = false];
   */
  captionTrackIndices: number[];

  /**
   * @generated from field: optional int32 defaultCaptionTrackIndex = 3;
   */
  defaultCaptionTrackIndex?: number;

  /**
   * @generated from field: optional int32 forcedCaptionTrackIndex = 4;
   */
  forcedCaptionTrackIndex?: number;

  /**
   * @generated from field: optional int32 visibility = 5;
   */
  visibility?: number;

  /**
   * @generated from field: optional bool hasDefaultTrack = 6;
   */
  hasDefaultTrack?: boolean;

  /**
   * @generated from field: optional bool hasForcedTrack = 7;
   */
  hasForcedTrack?: boolean;

  /**
   * @generated from field: optional string audioTrackId = 8;
   */
  audioTrackId?: string;

  /**
   * @generated from field: optional int32 captionsInitialState = 11;
   */
  captionsInitialState?: number;

  constructor(data?: PartialMessage<AudioTrack>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.AudioTrack";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AudioTrack;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AudioTrack;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AudioTrack;

  static equals(a: AudioTrack | PlainMessage<AudioTrack> | undefined, b: AudioTrack | PlainMessage<AudioTrack> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.TranslationLanguage
 */
export declare class TranslationLanguage extends Message<TranslationLanguage> {
  /**
   * @generated from field: string languageCode = 1;
   */
  languageCode: string;

  /**
   * @generated from field: youtube.response.player.Name languageName = 2;
   */
  languageName?: Name;

  constructor(data?: PartialMessage<TranslationLanguage>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.TranslationLanguage";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TranslationLanguage;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TranslationLanguage;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TranslationLanguage;

  static equals(a: TranslationLanguage | PlainMessage<TranslationLanguage> | undefined, b: TranslationLanguage | PlainMessage<TranslationLanguage> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.Name
 */
export declare class Name extends Message<Name> {
  /**
   * @generated from field: repeated youtube.response.player.Name.Run runs = 1;
   */
  runs: Name_Run[];

  constructor(data?: PartialMessage<Name>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.Name";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Name;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Name;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Name;

  static equals(a: Name | PlainMessage<Name> | undefined, b: Name | PlainMessage<Name> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.Name.Run
 */
export declare class Name_Run extends Message<Name_Run> {
  /**
   * @generated from field: string text = 1;
   */
  text: string;

  constructor(data?: PartialMessage<Name_Run>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.Name.Run";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Name_Run;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Name_Run;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Name_Run;

  static equals(a: Name_Run | PlainMessage<Name_Run> | undefined, b: Name_Run | PlainMessage<Name_Run> | undefined): boolean;
}

