// @generated by protoc-gen-es v1.7.2
// @generated from file response/player.proto (package youtube.response.player, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.response.player.Player
 */
export const Player = proto3.makeMessageType(
  "youtube.response.player.Player",
  () => [
    { no: 7, name: "adPlacements", kind: "message", T: AdPlacement, repeated: true },
    { no: 68, name: "adSlots", kind: "message", T: AdSlot, repeated: true },
    { no: 2, name: "playabilityStatus", kind: "message", T: PlayabilityStatus },
    { no: 9, name: "playbackTracking", kind: "message", T: PlaybackTracking },
    { no: 10, name: "captions", kind: "message", T: Captions },
  ],
);

/**
 * @generated from message youtube.response.player.AdPlacement
 */
export const AdPlacement = proto3.makeMessageType(
  "youtube.response.player.AdPlacement",
  () => [
    { no: 84813246, name: "adPlacementRenderer", kind: "message", T: AdPlacementRenderer },
  ],
);

/**
 * @generated from message youtube.response.player.AdPlacementRenderer
 */
export const AdPlacementRenderer = proto3.makeMessageType(
  "youtube.response.player.AdPlacementRenderer",
  () => [
    { no: 4, name: "params", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message youtube.response.player.PlayabilityStatus
 */
export const PlayabilityStatus = proto3.makeMessageType(
  "youtube.response.player.PlayabilityStatus",
  () => [
    { no: 21, name: "pictureInPictureRender", kind: "message", T: PictureInPictureSupportedRenderer },
    { no: 11, name: "backgroundPlayerRender", kind: "message", T: BackgroundSupportedRenderer },
  ],
);

/**
 * @generated from message youtube.response.player.PictureInPictureSupportedRenderer
 */
export const PictureInPictureSupportedRenderer = proto3.makeMessageType(
  "youtube.response.player.PictureInPictureSupportedRenderer",
  () => [
    { no: 151635310, name: "pictureInPictureAbility", kind: "message", T: PictureInPictureAbility },
  ],
);

/**
 * @generated from message youtube.response.player.BackgroundSupportedRenderer
 */
export const BackgroundSupportedRenderer = proto3.makeMessageType(
  "youtube.response.player.BackgroundSupportedRenderer",
  () => [
    { no: 64657230, name: "backgroundAbility", kind: "message", T: BackgroundAbility },
  ],
);

/**
 * @generated from message youtube.response.player.PictureInPictureAbility
 */
export const PictureInPictureAbility = proto3.makeMessageType(
  "youtube.response.player.PictureInPictureAbility",
  () => [
    { no: 1, name: "active", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "f4", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "f6", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "f8", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message youtube.response.player.BackgroundAbility
 */
export const BackgroundAbility = proto3.makeMessageType(
  "youtube.response.player.BackgroundAbility",
  () => [
    { no: 1, name: "active", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message youtube.response.player.PlaybackTracking
 */
export const PlaybackTracking = proto3.makeMessageType(
  "youtube.response.player.PlaybackTracking",
  () => [
    { no: 1, name: "videostatsPlaybackUrl", kind: "message", T: Url },
    { no: 2, name: "videostatsDelayplayUrl", kind: "message", T: Url },
    { no: 3, name: "videostatsWatchtimeUrl", kind: "message", T: Url },
    { no: 4, name: "ptrackingUrl", kind: "message", T: Url },
    { no: 5, name: "qoeUrl", kind: "message", T: Url },
    { no: 13, name: "atrUrl", kind: "message", T: Url },
    { no: 15, name: "videostatsEngageUrl", kind: "message", T: Url },
    { no: 18, name: "pageadViewthroughconversion", kind: "message", T: Url },
  ],
);

/**
 * @generated from message youtube.response.player.Url
 */
export const Url = proto3.makeMessageType(
  "youtube.response.player.Url",
  () => [
    { no: 1, name: "baseUrl", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message youtube.response.player.AdSlot
 */
export const AdSlot = proto3.makeMessageType(
  "youtube.response.player.AdSlot",
  () => [
    { no: 424701016, name: "render", kind: "message", T: AdSlot_Render },
  ],
);

/**
 * @generated from message youtube.response.player.AdSlot.Render
 */
export const AdSlot_Render = proto3.makeMessageType(
  "youtube.response.player.AdSlot.Render",
  [],
  {localName: "AdSlot_Render"},
);

/**
 * @generated from message youtube.response.player.Captions
 */
export const Captions = proto3.makeMessageType(
  "youtube.response.player.Captions",
  () => [
    { no: 51621377, name: "playerCaptionsTrackListRenderer", jsonName: "playerCaptionsTracklistRenderer", kind: "message", T: PlayerCaptionsTrackListRenderer },
  ],
);

/**
 * @generated from message youtube.response.player.PlayerCaptionsTrackListRenderer
 */
export const PlayerCaptionsTrackListRenderer = proto3.makeMessageType(
  "youtube.response.player.PlayerCaptionsTrackListRenderer",
  () => [
    { no: 1, name: "captionTracks", kind: "message", T: CaptionTrack, repeated: true },
    { no: 2, name: "audioTracks", kind: "message", T: AudioTrack, repeated: true },
    { no: 3, name: "translationLanguages", kind: "message", T: TranslationLanguage, repeated: true },
    { no: 4, name: "defaultAudioTrackIndex", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 6, name: "defaultCaptionTrackIndex", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
  ],
);

/**
 * @generated from message youtube.response.player.CaptionTrack
 */
export const CaptionTrack = proto3.makeMessageType(
  "youtube.response.player.CaptionTrack",
  () => [
    { no: 1, name: "baseUrl", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "message", T: Name },
    { no: 3, name: "vssId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "languageCode", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "kind", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "rtl", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 7, name: "isTranslatable", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message youtube.response.player.AudioTrack
 */
export const AudioTrack = proto3.makeMessageType(
  "youtube.response.player.AudioTrack",
  () => [
    { no: 2, name: "captionTrackIndices", kind: "scalar", T: 5 /* ScalarType.INT32 */, repeated: true, packed: false },
    { no: 3, name: "defaultCaptionTrackIndex", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 4, name: "forcedCaptionTrackIndex", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 5, name: "visibility", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 6, name: "hasDefaultTrack", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 7, name: "hasForcedTrack", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 8, name: "audioTrackId", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 11, name: "captionsInitialState", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
  ],
);

/**
 * @generated from message youtube.response.player.TranslationLanguage
 */
export const TranslationLanguage = proto3.makeMessageType(
  "youtube.response.player.TranslationLanguage",
  () => [
    { no: 1, name: "languageCode", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "languageName", kind: "message", T: Name },
  ],
);

/**
 * @generated from message youtube.response.player.Name
 */
export const Name = proto3.makeMessageType(
  "youtube.response.player.Name",
  () => [
    { no: 1, name: "runs", kind: "message", T: Name_Run, repeated: true },
  ],
);

/**
 * @generated from message youtube.response.player.Name.Run
 */
export const Name_Run = proto3.makeMessageType(
  "youtube.response.player.Name.Run",
  () => [
    { no: 1, name: "text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "Name_Run"},
);

