// @generated by protoc-gen-es v1.7.2
// @generated from file response/setting.proto (package youtube.response.setting, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.response.setting.Setting
 */
export declare class Setting extends Message<Setting> {
  /**
   * @generated from field: repeated youtube.response.setting.SettingItem settingItems = 6;
   */
  settingItems: SettingItem[];

  /**
   * @generated from field: repeated youtube.response.setting.SettingItem collectionItems = 7;
   */
  collectionItems: SettingItem[];

  /**
   *  St1F7 st1F7 = 7;
   *
   * @generated from field: youtube.response.setting.TrackingParams trackingParams = 10;
   */
  trackingParams?: TrackingParams;

  constructor(data?: PartialMessage<Setting>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.Setting";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Setting;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Setting;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Setting;

  static equals(a: Setting | PlainMessage<Setting> | undefined, b: Setting | PlainMessage<Setting> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.SettingItem
 */
export declare class SettingItem extends Message<SettingItem> {
  /**
   * @generated from field: youtube.response.setting.BackgroundPlayBackSettingRenderer backgroundPlayBackSettingRenderer = 88478200;
   */
  backgroundPlayBackSettingRenderer?: BackgroundPlayBackSettingRenderer;

  /**
   * @generated from field: youtube.response.setting.SettingCategoryCollectionRenderer settingCategoryCollectionRenderer = 66930374;
   */
  settingCategoryCollectionRenderer?: SettingCategoryCollectionRenderer;

  constructor(data?: PartialMessage<SettingItem>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.SettingItem";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SettingItem;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SettingItem;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SettingItem;

  static equals(a: SettingItem | PlainMessage<SettingItem> | undefined, b: SettingItem | PlainMessage<SettingItem> | undefined): boolean;
}

/**
 * message  St1F7{
 *  SettingCategoryEntryRenderer settingCategoryEntryRenderer = 88478200;
 * }
 *
 * @generated from message youtube.response.setting.TrackingParams
 */
export declare class TrackingParams extends Message<TrackingParams> {
  /**
   * @generated from field: int32 f1 = 1;
   */
  f1: number;

  /**
   * @generated from field: int32 f2 = 2;
   */
  f2: number;

  /**
   * @generated from field: int32 f3 = 3;
   */
  f3: number;

  /**
   * @generated from field: youtube.response.setting.TimeInfo timeInfo = 4;
   */
  timeInfo?: TimeInfo;

  constructor(data?: PartialMessage<TrackingParams>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.TrackingParams";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TrackingParams;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TrackingParams;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TrackingParams;

  static equals(a: TrackingParams | PlainMessage<TrackingParams> | undefined, b: TrackingParams | PlainMessage<TrackingParams> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.TimeInfo
 */
export declare class TimeInfo extends Message<TimeInfo> {
  /**
   * @generated from field: uint64 timestamp = 1 [jstype = JS_STRING];
   */
  timestamp: string;

  /**
   * @generated from field: fixed32 f2 = 2;
   */
  f2: number;

  /**
   * @generated from field: fixed32 f3 = 3;
   */
  f3: number;

  constructor(data?: PartialMessage<TimeInfo>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.TimeInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TimeInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TimeInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TimeInfo;

  static equals(a: TimeInfo | PlainMessage<TimeInfo> | undefined, b: TimeInfo | PlainMessage<TimeInfo> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.SettingCategoryEntryRenderer
 */
export declare class SettingCategoryEntryRenderer extends Message<SettingCategoryEntryRenderer> {
  /**
   * @generated from field: int32 f2 = 2;
   */
  f2: number;

  /**
   * @generated from field: int32 f3 = 3;
   */
  f3: number;

  /**
   * @generated from field: youtube.response.setting.TrackingParams trackingParams = 5;
   */
  trackingParams?: TrackingParams;

  /**
   * @generated from field: int32 f6 = 6;
   */
  f6: number;

  /**
   * @generated from field: int32 f7 = 7;
   */
  f7: number;

  /**
   * @generated from field: int32 f8 = 8;
   */
  f8: number;

  /**
   * @generated from field: int32 f9 = 9;
   */
  f9: number;

  /**
   * @generated from field: int32 f10 = 10;
   */
  f10: number;

  /**
   * @generated from field: int32 f12 = 12;
   */
  f12: number;

  constructor(data?: PartialMessage<SettingCategoryEntryRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.SettingCategoryEntryRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SettingCategoryEntryRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SettingCategoryEntryRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SettingCategoryEntryRenderer;

  static equals(a: SettingCategoryEntryRenderer | PlainMessage<SettingCategoryEntryRenderer> | undefined, b: SettingCategoryEntryRenderer | PlainMessage<SettingCategoryEntryRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.SettingCategoryCollectionRenderer
 */
export declare class SettingCategoryCollectionRenderer extends Message<SettingCategoryCollectionRenderer> {
  /**
   * @generated from field: repeated youtube.response.setting.SubSetting subSettings = 3;
   */
  subSettings: SubSetting[];

  /**
   * @generated from field: int32 categoryId = 4;
   */
  categoryId: number;

  constructor(data?: PartialMessage<SettingCategoryCollectionRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.SettingCategoryCollectionRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SettingCategoryCollectionRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SettingCategoryCollectionRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SettingCategoryCollectionRenderer;

  static equals(a: SettingCategoryCollectionRenderer | PlainMessage<SettingCategoryCollectionRenderer> | undefined, b: SettingCategoryCollectionRenderer | PlainMessage<SettingCategoryCollectionRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.SubSetting
 */
export declare class SubSetting extends Message<SubSetting> {
  /**
   * @generated from field: youtube.response.setting.SettingBooleanRenderer settingBooleanRenderer = 61331416;
   */
  settingBooleanRenderer?: SettingBooleanRenderer;

  constructor(data?: PartialMessage<SubSetting>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.SubSetting";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubSetting;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubSetting;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubSetting;

  static equals(a: SubSetting | PlainMessage<SubSetting> | undefined, b: SubSetting | PlainMessage<SubSetting> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.SettingBooleanRenderer
 */
export declare class SettingBooleanRenderer extends Message<SettingBooleanRenderer> {
  /**
   * @generated from field: youtube.response.setting.ServiceEndpoint enableServiceEndpoint = 5;
   */
  enableServiceEndpoint?: ServiceEndpoint;

  /**
   * @generated from field: youtube.response.setting.ServiceEndpoint disableServiceEndpoint = 6;
   */
  disableServiceEndpoint?: ServiceEndpoint;

  /**
   * @generated from field: youtube.response.setting.TrackingParams clickTrackingParams = 13;
   */
  clickTrackingParams?: TrackingParams;

  /**
   * @generated from field: int32 itemId = 15;
   */
  itemId: number;

  constructor(data?: PartialMessage<SettingBooleanRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.SettingBooleanRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SettingBooleanRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SettingBooleanRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SettingBooleanRenderer;

  static equals(a: SettingBooleanRenderer | PlainMessage<SettingBooleanRenderer> | undefined, b: SettingBooleanRenderer | PlainMessage<SettingBooleanRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.ServiceEndpoint
 */
export declare class ServiceEndpoint extends Message<ServiceEndpoint> {
  /**
   * @generated from field: youtube.response.setting.TrackingParams trackingParams = 2;
   */
  trackingParams?: TrackingParams;

  /**
   * @generated from field: youtube.response.setting.SetClientSettingEndpoint setClientSettingEndpoint = 81212182;
   */
  setClientSettingEndpoint?: SetClientSettingEndpoint;

  constructor(data?: PartialMessage<ServiceEndpoint>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.ServiceEndpoint";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServiceEndpoint;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServiceEndpoint;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServiceEndpoint;

  static equals(a: ServiceEndpoint | PlainMessage<ServiceEndpoint> | undefined, b: ServiceEndpoint | PlainMessage<ServiceEndpoint> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.SetClientSettingEndpoint
 */
export declare class SetClientSettingEndpoint extends Message<SetClientSettingEndpoint> {
  /**
   * @generated from field: youtube.response.setting.SettingDatas settingData = 1;
   */
  settingData?: SettingDatas;

  constructor(data?: PartialMessage<SetClientSettingEndpoint>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.SetClientSettingEndpoint";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetClientSettingEndpoint;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetClientSettingEndpoint;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetClientSettingEndpoint;

  static equals(a: SetClientSettingEndpoint | PlainMessage<SetClientSettingEndpoint> | undefined, b: SetClientSettingEndpoint | PlainMessage<SetClientSettingEndpoint> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.SettingDatas
 */
export declare class SettingDatas extends Message<SettingDatas> {
  /**
   * @generated from field: youtube.response.setting.ClientSettingEnum clientSettingEnum = 1;
   */
  clientSettingEnum?: ClientSettingEnum;

  /**
   * @generated from field: bool boolValue = 3;
   */
  boolValue: boolean;

  constructor(data?: PartialMessage<SettingDatas>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.SettingDatas";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SettingDatas;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SettingDatas;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SettingDatas;

  static equals(a: SettingDatas | PlainMessage<SettingDatas> | undefined, b: SettingDatas | PlainMessage<SettingDatas> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.ClientSettingEnum
 */
export declare class ClientSettingEnum extends Message<ClientSettingEnum> {
  /**
   * @generated from field: int32 item = 1;
   */
  item: number;

  constructor(data?: PartialMessage<ClientSettingEnum>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.ClientSettingEnum";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClientSettingEnum;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClientSettingEnum;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClientSettingEnum;

  static equals(a: ClientSettingEnum | PlainMessage<ClientSettingEnum> | undefined, b: ClientSettingEnum | PlainMessage<ClientSettingEnum> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.BackgroundPlayBackSettingRenderer
 */
export declare class BackgroundPlayBackSettingRenderer extends Message<BackgroundPlayBackSettingRenderer> {
  /**
   * @generated from field: youtube.response.setting.Label name = 1;
   */
  name?: Label;

  /**
   * @generated from field: bool backgroundPlayback = 2;
   */
  backgroundPlayback: boolean;

  /**
   * @generated from field: bool download = 3;
   */
  download: boolean;

  /**
   * @generated from field: bytes trackingParams = 5;
   */
  trackingParams: Uint8Array;

  /**
   * @generated from field: bool downloadQualitySelection = 9;
   */
  downloadQualitySelection: boolean;

  /**
   * @generated from field: bool smartDownload = 10;
   */
  smartDownload: boolean;

  /**
   * @generated from field: youtube.response.setting.Icon icon = 14;
   */
  icon?: Icon;

  constructor(data?: PartialMessage<BackgroundPlayBackSettingRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.BackgroundPlayBackSettingRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BackgroundPlayBackSettingRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BackgroundPlayBackSettingRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BackgroundPlayBackSettingRenderer;

  static equals(a: BackgroundPlayBackSettingRenderer | PlainMessage<BackgroundPlayBackSettingRenderer> | undefined, b: BackgroundPlayBackSettingRenderer | PlainMessage<BackgroundPlayBackSettingRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.Label
 */
export declare class Label extends Message<Label> {
  /**
   * @generated from field: repeated youtube.response.setting.Run runs = 1;
   */
  runs: Run[];

  constructor(data?: PartialMessage<Label>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.Label";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Label;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Label;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Label;

  static equals(a: Label | PlainMessage<Label> | undefined, b: Label | PlainMessage<Label> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.Run
 */
export declare class Run extends Message<Run> {
  /**
   * @generated from field: string text = 1;
   */
  text: string;

  constructor(data?: PartialMessage<Run>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.Run";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Run;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Run;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Run;

  static equals(a: Run | PlainMessage<Run> | undefined, b: Run | PlainMessage<Run> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.Icon
 */
export declare class Icon extends Message<Icon> {
  /**
   * @generated from field: int32 iconType = 1;
   */
  iconType: number;

  constructor(data?: PartialMessage<Icon>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.Icon";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Icon;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Icon;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Icon;

  static equals(a: Icon | PlainMessage<Icon> | undefined, b: Icon | PlainMessage<Icon> | undefined): boolean;
}

